### ISSUE TITLE
pre-commit hook invalid value

### ISSUE THREAD

**Issue by ale-ben** [datarootsio/databooks#27]
Using pre-commit hook generates the following error:
```
databooks................................................................Failed
- hook id: databooks
- exit code: 2

Usage: databooks meta [OPTIONS] PATHS...

Error: Invalid value: No prefix nor suffix were passed. Please specify `--overwrite` or `-w` to overwrite files.
```

this is the `.pre-commit-config.yaml`
```
repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.1.0
    hooks:
    -   id: trailing-whitespace
    -   id: end-of-file-fixer
    -   id: check-yaml
    -   id: check-added-large-files
-   repo: https://github.com/psf/black
    rev: 22.1.0
    hooks:
    -   id: black-jupyter
        language_version: python3.9
-   repo: https://github.com/datarootsio/databooks
    rev: 0.1.15
    hooks:
    -   id: databooks
```

**Comment by murilo-cunha** [comment]
As of now, you need to pass in the `--check` argument in `pre-commit`
```yaml
repos:
-   repo: https://github.com/datarootsio/databooks
    rev: 0.1.15
    hooks:
    -   id: databooks
        args: ["--overwrite"]
```
Check out [docs](https://datarootsio.github.io/databooks/0.1.15/usage/precommit/#configuration) for more info! 🚀
